### ISSUE TITLE
Getting Unix domain socket error with Postgres

### ISSUE THREAD

**Issue by secondstreetmedia** [SamSaffron/message_bus#123]
Hi,

The following error is appearing in both the log for my local Puma server as well as in the log when I'm pushing to Heroku:

    /Users/my-mac/.rvm/gems/ruby-2.2.4@chat/bundler/gems/message_bus-3415039a3b4b/lib/message_bus.rb:456:in `block in new_subscriber_thread'
    W, [2016-07-28T00:05:40.942790 #3250]  WARN -- : could not connect to server: No such file or directory
      Is the server running locally and accepting
      connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"?
      subscribe failed, reconnecting in 1 second. Call stack

Any idea what might be the cause? In the push to Heroku, it appears twice, when it is precompiling assets and when it cleans them. I've gone through a bunch of SO suggested solutions, but they lead to other things to try which lead to other things to try, none of which end up solving the problem. I'm currently working on two apps and I'm not seeing this error on the second app, which isn't using Message Bus. Just wondering if anyone has seen this and whether it's related to Message Bus or just coincidence.  Thanks!

(Rails 4.2.5, Devise, Postgres 4.5.3 - I originally had the Homebrew installation, but unsure if it was the source of the error, I uninstalled it, got rid of all files/folders postgres related, then reinstalled with Postgres.app, but the error remains.)

**Comment by jeremyevans** [comment]
It looks like you aren't configuring the PostgreSQL connection correctly (see https://github.com/SamSaffron/message_bus#postgresql).  The hash you provide to :backend_options is passed to `PG::Connection#initialize`.  You probably need to provide an appropriate hash, my guess is you are missing the :host option.  Heroku doesn't run a PostgreSQL instance inside your application dyno, so there's no local socket, that's why it is failing there.

**Comment by SamSaffron** [comment]
@secondstreetmedia this looks to be config related, did you sort this out?
