### ISSUE TITLE
When setting MessageBus.clientId the server crashes!

### ISSUE THREAD

**Issue by zeitnot** [SamSaffron/message_bus#85]
[Here](https://gist.github.com/zeitnot/e8f044fbd4279f9dcb90) is the server output.

**Comment by SamSaffron** [comment]
Sorry, what is the exact repro? is this happening on beta?

**Comment by zeitnot** [comment]
I am using the master branch.

**Comment by zeitnot** [comment]
@SamSaffron the server throws a different kind of error right now. [Here](https://gist.github.com/zeitnot/60f3636199ed198f5225) is the new one. I want to express again that this only happens when custom clientId set by manually like following.
`MessageBus.clientId = 'custom client id'`

**Comment by SamSaffron** [comment]
hmmm why are you setting clientId? this will only cause trouble it is meant to be unique per web client.

**Comment by zeitnot** [comment]
I am setting unique clientId per client. I am setting this because I want
to sent client based messages. Suppose that a user has 2 open browsers.  I
want a message from one to other. I can do it only with client id. For
example to avoid simultaneous login.

**Comment by SamSaffron** [comment]
wait can you expand a bit. 

If you need to publish a message from client1 to say all other clients for that user you can make a POST to the server, have it publish the message and then discard it on client1

I would not avoid simultaneous logins, instead there are a few options.

1. Use cross tab communication to notify another tab that your tab logged on
2. If only one user is allowed to be logged in on one tab at any point it time, I would post a "refresh" message to all the other tabs/browsers via the message bus. 

Can you expand a bit more on the exact use case with as many details as possible?

**Comment by zeitnot** [comment]
Suppose that we have a rails app supported by devise authentication. There is a user. This user would have the ability of killing other open sessions like facebook or gmail. At he backend it is simple. But While killing other sessions I want to send a message says 'This session is killed and you are logged out' if the web page currently open. With `user_id` I can't do that because it is logged out for that session. I can only send this message with `client_id` which set by the app for every session. So a user would have multiple `client_id`. This means that this user has multiple open sessions. Thus I would send a message to this user's browsers with `client_id` without `user_id`.  Definitely I do not understand your approachs.

**Comment by zeitnot** [comment]
Now I have created a workaround with sidekiq which I do not like. I have worker. This worker does killing the specified session after MessageBus sends the message to the related session. This is the only way I could find. But this is not good. If this gem gives me selecting my custom `client_id` it would be so good.

**Comment by SamSaffron** [comment]
> I want to send a message says 'This session is killed and you are logged out'

That is super easy:

```
MessageBus.publish('/logout', 'user logged out', user_id: 100)
```

Then the app handles that message and informs user in browser, we do that in Discourse, have been doing it for years.

**Comment by ffabreti** [comment]
I understand what @zeitnot is trying to achieve. He is trying to use client_id as a unique session identification, so `/logout` channel spread the logout of a session (identified by client_id) and not the logout of a user. (because a user as many client_ids)

So, publishing like @SamSaffron suggested: `MessageBus.publish('/logout', 'user logged out', user_id: 100)` is not what he wants, since it would notify the logout of **all** user sessions. 

In the context, a client_id is the only necessary data to identify a session. Be it on the server or on the JS-Client.  But, of course, you can control when a user is effectively logout if all of his client_ids have logged out.

Using client_ids as session identifier is great because they are already generated by message_bus at each JS-client load and they are gone after JS-client exits.

Been said that, I think message_bus would have a way to let client_id be provided by the user, so that JS-Client would retrieve it from localStorage and keep using the same client_id that had been previously "processed" by server (like attaching the client_id to a Social-Login token validated by the server side, so that when the server see a pooling from a JS-Client it understand that pooling is coming from an authenticated client).

**Comment by zeitnot** [comment]
@ffabreti :+1: 
Good catch. I solved that like this: I am creating a unique client id for every client. I save those client ids to user database and btw I could know how many sessions are open. To send a message to a specific client I am creating a channel with that client id and listening it with following code. 

```javascript
var client_id = getCookie('client_id')
MessageBus.subscribe(client_id, function(data){})
```

**Comment by ffabreti** [comment]
>To send a message to a specific client I am creating a channel with that client id

Well, if it works for you... The problem for me is that I need to authenticate the js-client and I am working with social logins tokens. 
I am thinking of a flow like:
- JS-Client Posts `client_id + email + token` to Message_bus server
- Server controller validates token and associates `client_id` with token when token is valid
- JS-Client pools Server for messages
- Message_bus server retrieve `client_id` from URL and test if it has an valid token
- `user_id_lookup` proc always return the `client_id` if it has an valid token
- every publish is made setting `user_ids: ["clientId"]`
 
I wonder if there are better ways of doing this...

**Comment by SamSaffron** [comment]
note you can publish to the client id and access it these days, so I am not sure what is left here.
