### ISSUE TITLE
message_bus chat example with Rails (Jquery and Angular versions)

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#91]
Hi there,

   I would like to share [a Rails version of the chat example.](https://github.com/ffabreti/message_bus-chat-example.git)
   
   
> Rails 4.1 + Postgresql 9 + Puma + message_bus 2.0.0.beta (no REDIS)

   Just in case someone would like to start from Rails.
   
   I have made an angularJS version of message-bus.js, without Jquery dependency. [here it goes the diff](https://github.com/ffabreti/message_bus-chat-example/commit/2cf8a138cdf572868ec64b908ca6d95b127ae774)

Thanks for this amazing gem.

#### Edit
Docs should state clearly the existence of `message-bus-ajax.js`. See #97 
It adds an native JS ajax adapter to message-bus.js that works with angular code without JQuery.

**Comment by derekyau** [comment]
hey @ffabreti or @SamSaffron quick question for you guys... when running message bus inside an initializer (like its done in the chat app example), since my web server is threaded (unicorn, etc.) I'm running into this issue where when a message comes in, multiple threads receive and process it at the same time. This often happens in the same action being called multiple times. I know I could guard in the code against this, but is there a better way of having only one thread take it and the rest don't receive it? Alternatively I guess I can setup a side process that is single threaded... whats best practice here?

**Comment by ffabreti** [comment]
No clue, I am just a new user of the gem.
But I would start looking for rack hijack compatibility with your unicorn version...

**Comment by derekyau** [comment]
hi @ffabreti yeah I do have that block of code in my unicorn.rb hmm...

**Comment by ffabreti** [comment]
@derekyau : have you seen #102  ?
