### ISSUE TITLE
Chat example set header without JQuery  (using message-bus-ajax.js)

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#98]
How can I set header like [in chat example...](https://github.com/SamSaffron/message_bus/blob/fc367a176e08d10266805899e38687f7b28850b5/examples/chat/chat.rb#L124-L127)
```
MessageBus.ajax = function(args){
          args["headers"]["X-NAME"] = name;
          return $.ajax(args);
        };
```
... without JQuery support (using message-bus-ajax.js)  ?

tried this without success:
```
window.MessageBus.ajax = function(args){
       args = args || {};
       args["headers"]["X-NAME"] = name;
       return new XMLHttpRequest(args);
 };
```
Also tried: 
```
            window.MessageBus.ajax({
                headers: {
                    'X-name': function() { return currentUser; }
                }
            });
```
but it complains about a lot of other not defined options.

**Comment by ffabreti** [comment]
My problem is that I cannot set headers for `longPoller()` that is defined inside `start()` 
I need to set headers on pooling so that I can send username to backend keep registering user presence.

**Comment by SamSaffron** [comment]
@nathanstitt  any ideas here? do we need to improve the ajax implementation ?

**Comment by nathanstitt** [comment]
Hm, it does read and set headers [from the options](https://github.com/SamSaffron/message_bus/blob/master/assets/message-bus-ajax.js#L22-L24), but there isn't a way to set them exposed from outside MessageBus.  Maybe we should use an extend instead of set [where they're defined]( https://github.com/SamSaffron/message_bus/blob/master/assets/message-bus.js#L123)  ? 

If that sounds like a good idea I can whip it up pretty quickly.

**Comment by ffabreti** [comment]
Thanks Guys. 
Tested and it works great.
